### ISSUE TITLE
question re: the synchronization branch: never merged?

### ISSUE THREAD

**Issue by sfjava** [CoalMineSoftware/jStately#2]
Hi Brandon,

I noticed that there's a "synchronization" branch -- which seems it might help fix some occasional "state machine not started yet" exceptions I've seen (perhaps?) -- so, is there a reason you've never merged/PR'ed this synch branch back into master?

best, 

--dk

**Comment by HeyLookItsBrandon** [comment]
Hi Daniel,

Synchronization is something I was considering for a certain use case but didn't end up needing and never got around to fully testing. I wouldn't mind revisiting it, especially if there's a need for it.

But out of curiosity, are you using 2.0.0? The exception makes me think the issue is the one described in more detail at https://github.com/CoalMineSoftware/jStately/pull/1. There was a limitation that would cause that exception if, in the process of evaluating an input, a transition's `onTransition()` logic caused another call to `StateMachine#evaluateInput()`. Because the machine was technically in between states, there was a check that would fail.

Anyway, I would like to take another look at synchronization in the next couple days. I'll keep you posted.

**Comment by HeyLookItsBrandon** [comment]
Hi Daniel,

I thought you might be interested to know that there's a new version of the library available. It adds a new [`SynchronizedStateMachine`](https://github.com/CoalMineSoftware/jStately/blob/master/src/main/java/com/coalminesoftware/jstately/machine/SynchronizedStateMachine.java) that adds synchronization in a way similar to the way [`Collections.synchronizedList()`](http://hg.openjdk.java.net/jdk8/jdk8/jdk/file/687fd7c7986d/src/share/classes/java/util/Collections.java#l2058) approaches it.

There are some other changes that prevent the release from being backward compatible but the changes needed should be trivial.

Brandon

**Comment by sfjava** [comment]
Good morning, Brandon — thanks for the update, and this is “perfect timing”, as we were just about to pull in a story here at MQ/VLS to “update jStately to the latest version” :) and so it’s good to know that the “synchronization” issues/feature has been addressed as part of this latest update.

I’ll have to review that approach used by the Collections package — but that sounds right.

Thanks again and we’ll let you know how it goes! 
best,

—dk

Daniel Kopyc  //  daniel@sfjava.net  //  +1 415-335-2710
--------------------------------------------------------
